Se añade documento de arquitectura de software
Lufann/PARCHS pull request #7
Opened 2022-12-10 23:38 UTC by nick00las

Añadir el archivo de arquitectura a la main

2022-12-11 19:01 UTC, GadCoder approved these changes
PR aprobado

2022-12-11 22:45 UTC, Phantasmaa approved these changes
Aprobado

2022-12-12 03:02 UTC, OscarEd08 approved these changes

2022-12-12 03:13 UTC, LucAle02 requested changes
Estas usando la versión desactualizada del repositorio.

2022-12-12 03:13 UTC, PhoenixBlue02 requested changes
Falta actualizar la rama compañero

2022-12-12 03:13 UTC, Lufann requested changes
No aprobado :c

2022-12-12 03:58 UTC, OscarEd08 requested changes
No aprobado

2022-12-12 04:21 UTC, closed without merging